<a href="https://colab.research.google.com/github/CReies/U_Class2_Linear-Algebra/blob/main/Cuaderno_2_Tema_1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size=6 color="#0098CD">
Álgebra Lineal
</font>
<p></p>
<font size=6>
Tema 1b. Operaciones con matrices
</font>


In [1]:
# Importar bibliotecas
import numpy as np
import sympy as sp

### Matriz identidad

La matriz identidad, $I$, es una matriz cuadrada para la cual se cumple que $i_{ij} = 1$ si $i = j$ e $i_{ij} = 0$ si $i \neq j$. A continuación se muestra cómo crear una matriz identidad con [NumPy](https://numpy.org/).

In [9]:
n = int(input("What order do you want the matrix in?\n"))
I = np.eye(n)

print(I)

What order do you want the matrix in?
6


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

---
#### Ejercicio 1
---

>Genera la matriz identidad de orden 6 usando [SymPy](https://www.sympy.org/es/).

In [6]:
n = int(input("What order do you want the matrix in?\n"))
I = sp.eye(n)

I

What order do you want the matrix in?
6


Matrix([
[1, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0],
[0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 1]])

---
#### Ejercicio 2
---

Calcula $AI$ si
$ A = \begin{bmatrix}
2  & 3 & 4 \\
-1 & 4 & 0
\end{bmatrix}$. Usa NumPy.

In [11]:
A = np.array([[2, 3, 4], [-1, 4, 0]])
I3 = np.eye(3)

print(np.matmul(A, I3))

[[ 2.  3.  4.]
 [-1.  4.  0.]]


---
#### Ejercicio 3
---

Calcula $IA$ si
$ A = \begin{bmatrix}
2  & 3 & 4 \\
-1 & 4 & 0
\end{bmatrix}$. Usa SymPy.

In [13]:
A = sp.Matrix([[2, 3, 4], [-1, 4, 0]])
I2 = sp.eye(2)

print(I2 * A)

Matrix([[2, 3, 4], [-1, 4, 0]])


### Matriz potencia

$A^n = A \cdot A \cdot A ~...~ A$

---
#### Ejercicio 4
---

Halla $A^3$ si
$ A = \begin{bmatrix}
1  & 2 \\
-3 & 0
\end{bmatrix}$. Realiza el cálculo en forma manual, luego con SymPy y finalmente con NumPy. Comenta los resultados.

**Solución:**

$A=\begin{bmatrix}
1 & 2\\
-3 & 0
\end{bmatrix}$

$A^3 = \begin{bmatrix}
1 & 2\\
-3 & 0
\end{bmatrix} \times \begin{bmatrix}
1 & 2\\
-3 & 0
\end{bmatrix} \times \begin{bmatrix}
1 & 2\\
-3 & 0
\end{bmatrix} =
\begin{bmatrix}
(1)(1)+
\end{bmatrix}
$

In [19]:
A = np.array([[1, 2], [-3, 0]])

print(np.matmul(A, np.matmul(A, A)))

A = sp.Matrix([[1, 2], [-3, 0]])

print(A**3)

[[-11 -10]
 [ 15  -6]]
Matrix([[-11, -10], [15, -6]])


### Matriz transpuesta

---
#### Ejercicio 5
---

Consulta la definición de matriz transpuesta y agrégala en esta celda. Complementa la definición con un ejemplo.

---
#### Ejercicio 6
---

Genera una matriz $A$ de orden $3 \times 4$, con entradas enteras aleatorias en el intervalo $[-5, 10]$. Halla luego $A^T$.

In [24]:
A = np.random.randint(-5, 11, size=(50,200))
AT =  np.transpose(A)

print(A)
print(AT)

[[10  8  2 ... -1 -3  8]
 [ 6 -1 -5 ... -1 -1  7]
 [-3  9 -1 ...  7 -1  2]
 ...
 [ 0  2  9 ...  0  9 -4]
 [-5 -2  9 ... -5 10  7]
 [ 5  8  6 ... -2  8  9]]
[[10  6 -3 ...  0 -5  5]
 [ 8 -1  9 ...  2 -2  8]
 [ 2 -5 -1 ...  9  9  6]
 ...
 [-1 -1  7 ...  0 -5 -2]
 [-3 -1 -1 ...  9 10  8]
 [ 8  7  2 ... -4  7  9]]


---
#### Ejercicio 7
---

Repite el ejercicio anterior usando el método ```seed()``` con el fin de comparar los resultados con tus compañeros.

---
#### Ejercicio 8
---

Construye un ejemplo para mostrar que una matriz cuadrada es simétrica si $A^T = A$.

### Matriz inversa

Dada una matriz cuadrada $A$, su matriz inversa $A^{-1}$ es aquella que cumple $AA^{-1} = A^{-1}A = I_n$. La matriz inversa no siempre existe, si existe es única.

---
#### Ejercicio 9
---

Crea una matriz de orden $2 \times 2$ y calcula la inversa en forma manual. Comprueba que $AA^{-1} = A^{-1}A = I_n$.

**Solución:**

---
#### Ejercicio 10
---

Usa NumPy y SymPy para calcular la inversa de diferentes matrices cuadradas. ¿Qué respuesta se obtiene cuándo la inversa no existe?

### Determinante

Una matriz es invertible si, y solo si, su determinante es distinto de cero.

---
#### Ejercicio 11
---

Calcula el determinante de las matrices usadas en los ejercicios 9 y 10.

### Matrices booleanas

---
#### Ejercicio 12
---

Consulta las siguientes definiciones:

* Matriz intersección (meet)
* Matriz unión (join)
* Producto booleano, $A \odot B$

Elabora un ejemplo por cada definición usando NumPy y SymPy.



**Matriz intersección (meet):**

In [ ]:
# Ejemplo

**Matriz unión (join):**

In [ ]:
# Ejemplo

**Producto booleano, $A \odot B$:**

In [ ]:
# Ejemplo